version: "3"

services:
  integration-tests:
    image: cr:integration
    depends_on:
      - api
    env_file:
      - test.env
    networks:
      main:
        aliases:
          - integration_tests