version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    networks:
      main:
        aliases:
          - db
  migrations:
    build: ../migrations/.
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
    networks:
      main:
        aliases:
          - migrations
  stats_updater:
    build:
      dockerfile: ./build/stats/Dockerfile
      context: ../.
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      STATS_INTERVAL: 1
    networks:
      main:
        aliases:
          - stats_updater
  api:
    build:
      dockerfile: ./build/api/Dockerfile
      context: ../
    ports:
      - "8085:8085"
    depends_on:
      - db
      - migrations
      - stats_updater
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      API_PORT: 8085
    networks:
      main:
        aliases:
          - api
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
volumes:
  database:
networks:
  main:
    driver: bridge
