version: "3"

services:
  adminer:
    image: adminer:latest
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  swagger:
    build: ../api/swagger/.
    depends_on:
      - api
    environment:
      SWAGGER_JSON: /swagger.yml
    networks:
      main:
        aliases:
          - swagger
  proxy:
    image: nginx:mainline-alpine
    depends_on:
      - api
      - swagger
      - adminer
    ports:
      - "8080:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      main:
        aliases:
          - proxy