version: "3"

services:
  adminer:
    image: adminer:latest
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  swagger:
    image: swaggerapi/swagger-ui:latest
    depends_on:
      - api
    environment:
      SWAGGER_JSON: /swagger.yml
    volumes:
      - ./conf/swagger.yml:/swagger.yml
    networks:
      main:
        aliases:
          - swagger
  proxy:
    image: nginx:mainline-alpine
    depends_on:
      - api
      - swagger
      - adminer
    ports:
      - "8080:8080"
    volumes:
      - ./conf/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      main:
        aliases:
          - proxy