version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    networks:
      main:
        aliases:
          - db
  migrations:
    build: ../migrations/.
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
    networks:
      main:
        aliases:
          - migrations
  stats_updater:
    build:
      dockerfile: ./build/stats/Dockerfile
      context: ../.
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      STATS_INTERVAL: 1
    networks:
      main:
        aliases:
          - stats_updater
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  proxy:
    image: nginx:latest
    volumes:
      - ../configs/proxy:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - adminer:adminer
    depends_on:
      - adminer
    networks:
      main:
        aliases:
          - proxy
volumes:
  database:
networks:
  main:
    driver: bridge
