version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "${DB_PORT}:5432"
    networks:
      main:
        aliases:
          - db
  migrations:
    build: ../migrations/.
    depends_on:
      - db
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
    networks:
      main:
        aliases:
          - migrations
  rabbit:
    image: rabbitmq:3-alpine
    ports:
      - "${RABBIT_PORT}:5672"
    env_file:
      - rabbit.env
    networks:
      main:
        aliases:
          - rabbit
  stats_updater:
    image: cr:stats
    depends_on:
      - db
      - broker
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      STATS_INTERVAL: 1
    networks:
      main:
        aliases:
          - stats_updater
  api:
    image: cr:api
    depends_on:
      - db
      - migrations
      - stats_updater
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      API_PORT: 8080
    networks:
      main:
        aliases:
          - api
networks:
  main:
    driver: bridge
