TRUNCATE TABLE "stats";
TRUNCATE TABLE "slot_creative";
TRUNCATE TABLE "segment" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "creative" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "slot" RESTART IDENTITY CASCADE;