[LOGGER]
LOG_LEVEL = "debug"

[DB]
POSTGRES_HOST = "127.0.0.1"
POSTGRES_PORT = 8086
POSTGRES_DB = "creatives"
POSTGRES_USER = "cr_user"
POSTGRES_PASSWORD = "password"

[STATS]
INTERVAL = 1 #seconds

[API]
API_HOST = "127.0.0.1"
API_PORT = 8081

[QUEUE]
KAFKA_HOST = "127.0.0.1"
KAFKA_PORT = 9094