[LOGGER]
LOG_LEVEL = "debug"

[DB]
POSTGRES_HOST = "127.0.0.1"
POSTGRES_PORT = 8086
POSTGRES_DB = "creatives"
POSTGRES_USER = "cr_user"
POSTGRES_PASSWORD = "password"

[API]
API_HOST = "127.0.0.1"
API_PORT = 8081

[QUEUE]
RABBIT_HOST = "127.0.0.1"
RABBIT_PORT = 8087
RABBITMQ_DEFAULT_USER = "cr_user"
RABBITMQ_DEFAULT_PASS = "password"
