name: Creative Rotation app checks

on:
  push:
    branches:
      - '*'

env:
  GO111MODULE: "on"

jobs:
  creative-rotation-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: lint
        run: make lint
        working-directory: .

      - name: build
        run: make build
        working-directory: .

      - name: unit tests
        run: make test-unit
        working-directory: .

      - name: integration tests
        run: make run-integration-test
        working-directory: .
